### ISSUE TITLE
Extra quotation marks appear in python mode

### ISSUE THREAD

**Issue by MaggieLu** [convergencelabs/code-editor-demo#2] opened 2019-09-19 02:54 UTC
### Steps to Reproduce
1. set ace mode as python
2. create a file
3. type anything including `"" `or `''`, e.g. `print ("abc")`
4. close the file tab
5. reopen the file
### Actual Behavior
Extra double quotation marks appear, e.g. `print ("abc""""")`

### Expected Behavior
Show the original input code

**Comment by alalonde** [comment] 2019-09-19 21:23
Thanks for the bug report! We noticed this issue ourselves a couple years ago and discovered the root cause, as [reported here](https://github.com/orientechnologies/orientdb/issues/6250).  We put in a workaround, but that bug has since been fixed making the workaround the new source.  We've removed the workaround in the server code, which will be released in 1.0.0-rc.4.

**Comment by MaggieLu** [comment] 2019-09-20 02:35
Thanks, good to know. May I ask when the version will release?

**Comment by alalonde** [comment] 2019-09-24 17:59
We've got a lot going into this next release, so it will be a few weeks at least.

**Closed** 2019-09-24 17:59 UTC
